
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * billdetails.java
 *
 * Created on Oct 21, 2010, 5:40:22 PM
 */

/**
 *
 * @author dell
 */
public class billdetails extends javax.swing.JFrame {

    /** Creates new form billdetails */
    public billdetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exitbutton = new javax.swing.JButton();
        showdatabutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill no.", "Bill date", "Admit no.", "No. of Days", "Type of room", "Room charges", "Food charges", "X-ray", "Blood test", "Sugar test", "ECG", "Other charges", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        exitbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        showdatabutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showdatabutton.setText("Show Data");
        showdatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatabuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setText("Bill Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(showdatabutton)
                        .addGap(134, 134, 134)
                        .addComponent(exitbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showdatabutton)
                    .addComponent(exitbutton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void showdatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatabuttonActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
        Statement stmt=con.createStatement();
        String sql,billno,billdate,admno,days,typroom,roomcharge,food,xray,blood,sugar,ecg,othercharge,total;
        sql= "select * from bill";
        ResultSet rst=stmt.executeQuery(sql);
        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        while(rst.next())
        {billno=rst.getString("bill_no");
         billdate=rst.getString("bill_date");
         admno=rst.getString("admit_no");
         days=rst.getString("no_of_days");
         typroom=rst.getString("type_of_room");
         roomcharge=rst.getString("room_charges");
         food=rst.getString("food_charges");
         xray=rst.getString("x_ray");
         blood=rst.getString("blood_test");
         sugar=rst.getString("sugar_test");
         ecg=rst.getString("ecg");
         othercharge=rst.getString("other_charges");
         total=rst.getString("total");
         tm.addRow(new Object[]{billno,billdate,admno,days,typroom,roomcharge,food,xray,blood,sugar,ecg,othercharge,total});
        }
        jTable1.setModel(tm);
        rst.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_showdatabuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showdatabutton;
    // End of variables declaration//GEN-END:variables

}
