
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * discharge.java
 *
 * Created on Oct 21, 2010, 4:58:59 PM
 */

/**
 *
 * @author dell
 */
public class discharge extends javax.swing.JFrame {

    /** Creates new form discharge */
    public discharge() {
        initComponents();
        fillcombo();
    }
void fillcombo()
{    try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
            Statement stmt = con.createStatement();
            String sql;
            sql = "Select name from staff";
            ResultSet rst = stmt.executeQuery(sql);
            DefaultComboBoxModel dc = (DefaultComboBoxModel) cbdoc.getModel();
            while (rst.next())
            { dc.addElement(rst.getString(1));
            }
            cbdoc.setModel(dc);
            rst.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());
            }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        admnotf = new javax.swing.JTextField();
        admdatetf = new javax.swing.JTextField();
        patientnmtf = new javax.swing.JTextField();
        agetf = new javax.swing.JTextField();
        diseasetf = new javax.swing.JTextField();
        bednotf = new javax.swing.JTextField();
        wardtf = new javax.swing.JTextField();
        cbdoc = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        dischargedatetf = new javax.swing.JTextField();
        showdatabutton = new javax.swing.JButton();
        dischargebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel1.setText("Admit No.");

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel2.setText("Admit Date");

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel3.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel5.setText("Disease");

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel6.setText("Doctor Treating");

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel7.setText("Ward");

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel8.setText("Bed No.");

        buttonGroup1.add(rbmale);
        rbmale.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        rbmale.setText("Male");
        rbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        rbfemale.setText("Female");

        admnotf.setEditable(false);

        admdatetf.setEditable(false);

        patientnmtf.setEditable(false);

        agetf.setEditable(false);

        diseasetf.setEditable(false);
        diseasetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasetfActionPerformed(evt);
            }
        });

        bednotf.setEditable(false);

        wardtf.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel9.setText("Discharge Date");

        showdatabutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showdatabutton.setText("Show Data");
        showdatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatabuttonActionPerformed(evt);
            }
        });

        dischargebutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dischargebutton.setText("Discharge");
        dischargebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dischargebuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel10.setText("Patient Discharge Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showdatabutton)
                        .addGap(14, 14, 14)
                        .addComponent(dischargebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearbutton)
                        .addGap(18, 18, 18)
                        .addComponent(exitbutton))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(dischargedatetf, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wardtf, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(cbdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bednotf, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(admnotf, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(patientnmtf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(agetf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(diseasetf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(admdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbfemale)
                                    .addComponent(rbmale))))
                        .addGap(146, 146, 146)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(admnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(admdatetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patientnmtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(agetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbmale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(diseasetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(wardtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(bednotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(dischargedatetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showdatabutton)
                            .addComponent(dischargebutton)
                            .addComponent(clearbutton)
                            .addComponent(exitbutton))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbfemale)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diseasetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseasetfActionPerformed

    private void showdatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatabuttonActionPerformed
        // TODO add your handling code here:
       try{Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
        Statement stmt=con.createStatement();
        String sql,admno,gender;
        admno=JOptionPane.showInputDialog(this,"Enter Admit No. to Discharge");
        sql = "select * from patient where admit_no="+admno;
        ResultSet rst = stmt.executeQuery(sql);
        if(rst.next()==false)
            JOptionPane.showMessageDialog(null,"Invalid admit no.,Please try again");
        else
            admnotf.setText(rst.getString("admit_no"));
            admdatetf.setText(rst.getString("admit_date"));
            patientnmtf.setText(rst.getString("patient_name"));
            agetf.setText(rst.getString("age"));
            diseasetf.setText(rst.getString("disease"));
            wardtf.setText(rst.getString("ward"));
            bednotf.setText(rst.getString("bed_no"));
            dischargedatetf.setText(rst.getString("discharge_date"));
             gender=rst.getString("gender");
            if(gender.equalsIgnoreCase("male"))
                rbmale.setSelected(true);
            else if(gender.equalsIgnoreCase("female"))
                rbfemale.setSelected(true);
        rst.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_showdatabuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_exitbuttonActionPerformed

    private void dischargebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dischargebuttonActionPerformed
        // TODO add your handling code here:
        try{Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
        Statement stmt=con.createStatement();
        String sql,admno,sql1,dischargedate;
        dischargedate=dischargedatetf.getText();
        admno = admnotf.getText();
        if(admno.equals(""))
            JOptionPane.showMessageDialog(null,"Admit no. is empty,Kindly click Show Data");
        else
            {sql1 = "select admit_no from bill where admit_no="+admno+";";
             ResultSet rst = stmt.executeQuery(sql1);
             if (rst.next() == true)
                {
                    sql = "update patient set discharge_date='"+dischargedate+"' where admit_no="+admno+";";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Patient Discharged");
                     admnotf.setText("");
                     admdatetf.setText("");
                     patientnmtf.setText("");
                     agetf.setText("");
                     diseasetf.setText("");
                     wardtf.setText("");
                     bednotf.setText("");
                     dischargedatetf.setText("");
                }
           else
                {
                    JOptionPane.showMessageDialog(null,"First Generate Bill before discharge");
                }
            rst.close();
            }
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}

    }//GEN-LAST:event_dischargebuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        admnotf.setText("");
        admdatetf.setText("");
        patientnmtf.setText("");
        agetf.setText("");
        diseasetf.setText("");
        wardtf.setText("");
        bednotf.setText("");
        dischargedatetf.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void rbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmaleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new discharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admdatetf;
    private javax.swing.JTextField admnotf;
    private javax.swing.JTextField agetf;
    private javax.swing.JTextField bednotf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbdoc;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton dischargebutton;
    private javax.swing.JTextField dischargedatetf;
    private javax.swing.JTextField diseasetf;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField patientnmtf;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JButton showdatabutton;
    private javax.swing.JTextField wardtf;
    // End of variables declaration//GEN-END:variables

}
