
import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * modify.java
 *
 * Created on Oct 21, 2010, 3:03:18 PM
 */

/**
 *
 * @author dell
 */
public class modify extends javax.swing.JFrame {

    /** Creates new form modify */
    public modify() {
        initComponents();
        fillcombo();
    }
    void fillcombo()
{    try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
            Statement stmt = con.createStatement();
            String sql;
            sql = "Select distinct designation from staff";
            ResultSet rst = stmt.executeQuery(sql);
            DefaultComboBoxModel dsg = (DefaultComboBoxModel) cbdesignation.getModel();
            while (rst.next())
            { dsg.addElement(rst.getString(1));
            }
            cbdesignation.setModel(dsg);
            rst.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        residencephtf = new javax.swing.JTextField();
        mobilephtf = new javax.swing.JTextField();
        addresstf = new javax.swing.JTextField();
        qualificationtf = new javax.swing.JTextField();
        staffidtf = new javax.swing.JTextField();
        cbspecialisation = new javax.swing.JComboBox();
        cbdesignation = new javax.swing.JComboBox();
        agetf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        showdatabutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel1.setText("Staff Id");

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel4.setText("Designation");

        jLabel5.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel5.setText("Specialisation");

        jLabel6.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel6.setText("Qualification");

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel8.setText("Phone:");

        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel9.setText("Residence");

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 18));
        jLabel10.setText("Mobile");

        staffidtf.setEditable(false);
        staffidtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffidtfActionPerformed(evt);
            }
        });

        cbspecialisation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "General", "Ear", "Eye", "Skin", "Heart", "Brain", "Stomach" }));

        buttonGroup1.add(rbmale);
        rbmale.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        rbmale.setText("Male");

        buttonGroup1.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        rbfemale.setText("Female");
        rbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemaleActionPerformed(evt);
            }
        });

        showdatabutton.setFont(new java.awt.Font("Times New Roman", 1, 18));
        showdatabutton.setText("Show Data");
        showdatabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatabuttonActionPerformed(evt);
            }
        });

        updatebutton.setFont(new java.awt.Font("Times New Roman", 1, 18));
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Times New Roman", 1, 18));
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Times New Roman", 1, 18));
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel11.setText("Staff  Details Modification");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbspecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(staffidtf)
                                                    .addComponent(nametf)
                                                    .addComponent(agetf, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbmale)
                                                    .addComponent(rbfemale))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel9)
                                                            .addComponent(jLabel10)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(showdatabutton)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(28, 28, 28)
                                                        .addComponent(updatebutton)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(clearbutton)
                                                        .addGap(54, 54, 54)
                                                        .addComponent(exitbutton))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(residencephtf)
                                                            .addComponent(mobilephtf, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(qualificationtf, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                                    .addComponent(addresstf, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))))
                                        .addGap(110, 110, 110)))
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(staffidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbmale)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbfemale)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbspecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qualificationtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addresstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(residencephtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mobilephtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showdatabutton)
                    .addComponent(updatebutton)
                    .addComponent(clearbutton)
                    .addComponent(exitbutton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffidtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffidtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffidtfActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        staffidtf.setText("");
        nametf.setText("");
        agetf.setText("");
        qualificationtf.setText("");
        addresstf.setText("");
        residencephtf.setText("");
        mobilephtf.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void showdatabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatabuttonActionPerformed
        // TODO add your handling code here:
        try{Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
        Statement stmt=con.createStatement();
        String sql,staffid,gender;
        staffid = JOptionPane.showInputDialog(this,"Enter Staff id to modify");
        sql = "select * from staff where staff_id="+staffid;
        ResultSet rst = stmt.executeQuery(sql);
        if(rst.next()==false)
            JOptionPane.showMessageDialog(null,"Invalid staff id,Please Try Again");
        else
           staffidtf.setText(rst.getString("staff_id"));
            nametf.setText(rst.getString("name"));
            agetf.setText(rst.getString("age"));
            cbdesignation.setSelectedItem(rst.getString("designation"));
            cbspecialisation.setSelectedItem(rst.getString("specialisation"));
            qualificationtf.setText(rst.getString("qualification"));
            addresstf.setText(rst.getString("address"));
            residencephtf.setText(rst.getString("residence_phone"));
            mobilephtf.setText(rst.getString("mobile_phone"));
            gender=rst.getString("gender");
            if(gender.equalsIgnoreCase("male"))
                rbmale.setSelected(true);
            else if(gender.equalsIgnoreCase("female"))
                rbfemale.setSelected(true);
        rst.close();
        stmt.close();
        con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_showdatabuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        try{Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","root");
        Statement stmt = con.createStatement();
        String sql,staffid,name,age,qualification,address,resph,mobph,gender;
        name=nametf.getText();
        age=agetf.getText();
        Object designation=cbdesignation.getSelectedItem();
        Object specialisation=cbspecialisation.getSelectedItem();
        qualification=qualificationtf.getText();
        address=addresstf.getText();
        resph=residencephtf.getText();
        mobph=mobilephtf.getText();
        {if(rbmale.isSelected()==true)
            gender="male";
        else
            gender="female";
        }
        staffid = staffidtf.getText();
        if(staffid.equals(""))
            JOptionPane.showMessageDialog(null,"Staff id is empty,Kindly click Show Data");
        else
        {
          sql="update staff set name='"+name+"',age="+age+",designation='"+designation+"',specialisation='"+specialisation+"',qualification='"+qualification+"',address='"+address+"',residence_phone='"+resph+"',mobile_phone='"+mobph+"',gender='"+gender+"' where staff_id ="+staffid ;
          stmt.executeUpdate(sql);
          JOptionPane.showMessageDialog(this,"Record Updated Successfully");
          staffidtf.setText("");
          nametf.setText("");
          agetf.setText("");
          qualificationtf.setText("");
          addresstf.setText("");
          residencephtf.setText("");
          mobilephtf.setText("");
        }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void rbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemaleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstf;
    private javax.swing.JTextField agetf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbdesignation;
    private javax.swing.JComboBox cbspecialisation;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobilephtf;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField qualificationtf;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextField residencephtf;
    private javax.swing.JButton showdatabutton;
    private javax.swing.JTextField staffidtf;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables

}
